### ISSUE TITLE
Unquoted LOGGING variable in fuseki-server can make server fail to start

### ISSUE THREAD

**Issue by swartik** [apache/jena#1336]
In version 4.5.0 of Apache Jena Fuseki, line 117 is:

```shell
exec "$JAVA" $JVM_ARGS $LOGGING -cp "$CP" org.apache.jena.fuseki.cmd.FusekiCmd "$@"
```

`$LOGGING` is set using `$FUSEKI_HOME`. I define the `FUSEKI_HOME` variable in my environment. It has an embedded space. Consequently, the `fuseki-server` script expands the `LOGGING` variable into multiple arguments. Java doesn't parse the arguments as the script intends. Can/should `$LOGGING` be surrounded in double quotes?

**Comment by kinow** [comment]
Adding quotes should be ok and fix the issue here. Would you like to send a small pull request for that? Thanks!

**Comment by afs** [comment]
There is a corner case : suppose "$FUSEKI_HOME/log4j2.properties" does not exist then LOGGING isn't set and $LOGGING expands on the command line to no argument. But if it is quoted, it puts in an empty string argument. And because it has no leading "-" it cuts off the command flags.

What about:
```
elif [ ! -n "$LOGGING" ]
     LOGGING="'$LOGGING'"
fi
```
(that's double-quote, single quote ... single-quote, double-quote)

set LOGGING to have quotes and keep $LOGGING unquoted in the java line.

An alternative is to to set LOGGING to some no-op like `-Dnosuch=novalue`.

**Comment by swartik** [comment]
Good point. I will come up with a solution that can't insert an empty argument.

**Comment by swartik** [comment]
I've pushed another commit that quotes LOGGING if it's not empty.

The code assumes LOGGING will expand to a single argument. That is,

```shell
$ export LOGGING='-Dlog4j.configurationFile=myconfig.properties -DmyLogVar=value'
$ fuseki-server
```

won't work. I assume this isn't a problem, because the argument could be provided in JVM_ARGS. Let me know if I'm mistaken.

**Comment by afs** [comment]
No, shouldn't be a problem.

**Comment by swartik** [comment]
I think we're good to go, then. Let me know if there's anything else you need from me.
