### ISSUE TITLE
Getting null when using RIOT.getContext()

### ISSUE THREAD

**Issue by ebremer** [apache/jena#1360]
I have a java program that when I run it in the context of my IDE Netbeans, when making the call RIOT.getContext() as the first line will return:
```
symbol:http://jena.apache.org/ARQ#regexImpl = symbol:http://jena.apache.org/ARQ#javaRegex
symbol:http://jena.apache.org/ARQ#registryFunctions = org.apache.jena.sparql.function.FunctionRegistry@4659191b
symbol:http://jena.apache.org/ARQ#constantBNodeLabels = true
symbol:http://jena.apache.org/ARQ#registryPropertyFunctions = org.apache.jena.sparql.pfunction.PropertyFunctionRegistry@55634720
symbol:http://jena.apache.org/ARQ#stageGenerator = org.apache.jena.tdb2.solver.StageGeneratorDirectTDB@4b0d79fc
symbol:http://jena.apache.org/ARQ#enablePropertyFunctions = true
symbol:http://jena.apache.org/ARQ#registryServiceExecutors = org.apache.jena.sparql.service.ServiceExecutorRegistry@4c1909a3
symbol:http://jena.apache.org/ARQ#strictSPARQL = false
```
but, when I run the program using java -jar myprog.jar, ARQ.getContext() will return null.
My JDK:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)
```
Any thoughts to why this is happening?

**Comment by ebremer** [comment]
It will work outside Netbean using Maven:
 mvn exec:java -Dexec.mainClass="com.myworks.testprog"

but still returns null using the "java -jar" method.

**Comment by ebremer** [comment]
After some digging, I added:
        ARQ.init();

and now the expected results print.  I never had to do this before.  I suppose something is different in this new JDK I am using.

**Comment by afs** [comment]
This could be because the combined jar does not include the service loader files:

https://jena.apache.org/documentation/notes/jena-repack.html

For each of the jena jars included, the repacking needs to include (concatenate into one file) the contents of all
`META-INF/services/org.apache.jena.sys.JenaSubsystemLifecycle` files in one file in the combined jar.

These are what drives Jena initialization using Java ServiceLoader. The JenaSubsystemLifecycle in Jena calls ARQ.init amongst other things.

**Comment by ebremer** [comment]
That did the trick.  I was able to remove the ARQ.init() line after that.  The weird is that I've used a shaded jar in this project for years with Jena without needing this change, so I'm not sure what changed, but it's an easy enough change.  Thanks Andy!

**Comment by afs** [comment]
There was probably partial initialization - normally initialization happens when Jena is first touched by app code. An app can force it with `JenaSystem.init()`. There is still class initialization happening and `ARQ.init` can be triggered (or "was triggered") by other routes.

https://jena.apache.org/documentation/notes/system-initialization.html

including how to debug.
