### ISSUE TITLE
[Bug]: a property function is not invoked while processing QueryExecution created by QueryExecutionDatasetBuilder

### ISSUE THREAD

**Issue by sszuev** [apache/jena#1381]
### Version

4.6.0

### What happened?

For the query
```sparql
SELECT ?s WHERE {
    ?s <http://test#fun> ?o .
}
```
where `<http://test#fun>` is a custom property function, this code works as expected:
```java
DatasetGraph dg = new DatasetGraphWrapper(DatasetGraphFactory.wrap(data.getGraph()), context);
try (QueryExecution qe = QueryExecutionFactory.create(QueryFactory.create(query), dg)) {
...
}
```
but this one does not work:
```java
try (QueryExecution qe = QueryExecution.create().query(query).model(data).context(context).build()) {
...
}
```

from #1374 

full test is attached:
[TestQueryExecution.java.txt](https://github.com/apache/jena/files/8892919/TestQueryExecution.java.txt)
 

### Which environment is running?

- [ ] macOS
- [X] Windows
- [X] Linux
- [ ] other

**Comment by sszuev** [comment]
One of the possible fix is to replace the line `cxt = baseContext;` with the line `ctx = Context.mergeCopy(ARQ.getContext(), baseContext);` in `org.apache.jena.sparql.util.ContextAccumulator#buildContext`: https://github.com/apache/jena/blob/main/jena-arq/src/main/java/org/apache/jena/sparql/util/ContextAccumulator.java#L145).    

Not sure about side effects, but after this change there are no new fails of ARQ test.

**Comment by afs** [comment]
I have just found that property functions have to be explicitly enabled whereas custom functions do not which is why functions work and property functions don't in the test case.

Custom functions are part of SPARQL.
Property functions are an ARQ feature.

https://github.com/apache/jena/blob/ebb8b1202177c0dd74f88f808359497a38e8daf6/jena-arq/src/main/java/org/apache/jena/sparql/algebra/optimize/TransformPropertyFunction.java#L54

The DatasetGraphWrapper case merges in ARQ.getContext which has this set.
`new Context()` does not.

Try this with and without the `cxt.put`:
```
    private static Context testContext(int id) {
        Context cxt = new Context() {
            @Override
            public String toString() {
                return "TestContext#" + id;
            }
        };
        cxt.put(ARQ.enablePropertyFunctions, true); 
        return cxt;
    }
```
That said, the defaults are confusing and silly.

It can be `isTrueOrUndef` in `TransformPropertyFunction`.
`strictMode` turns property functions off explicitly so the system default behaviour does not need to be "off".

It took me a long time to see why even my minimal case based on your test case (thank you!) wasn't working.

Sorry for all the trouble.
