### ISSUE TITLE
rsparql and custom collection functions

### ISSUE THREAD

**Issue by SimonBin** [apache/jena#1526]
### Version

4.6.1

### Question

When I try to use rsparql to execute such a query:

```sparql
PREFIX set: <http://jsa.aksw.org/fn/set/>
select
?s1
(set:collect(?loc2) as ?loc2s)
{
}
group by ?s1
```
against a remote fuseki server:

> `rsparql --service http://localhost:3030/ds2/ --query testcase.sparql`

where set:collect is a custom aggregation function registered on the service (thus it is not known to rsparql) I get an error such as 

```
Non-group key variable in SELECT: ?loc2 in expression (<http://jsa.aksw.org/fn/set/collect> ?loc2)
```

is this a bug?

**Comment by afs** [comment]
Is the error before the request is sent?

That would be because `rsparql` doesn't know that it is an aggregate function. Aggregators have to be declared to be parsed correctly otherwise they look like plain function calls.

You could add custom Jena initialization code to the classpath to declare the aggregates.

Or when the far end is ARQ, you can use the AGG syntax to indicate an aggregate.

```
select ?s1 (AGG set:collect(?loc2) as ?loc2s) {
```

except `rsparql` accepts strict SPARQL 1.1 so it needs a tweak for that.

**Comment by SimonBin** [comment]
yes the error comes and the request is never sent. I was wondering if `rsparql` was a better `curl`, so to speak, but I guess it doesn't easily work with custom aggregators because they won't be parsed correctly without additional work.

**Comment by afs** [comment]
c.f. SOH `s-query`

Though `curl` is fine.

Fuseki servers have "?format=text" if you want the server to text type results. Or pipeto `rset`.

**Comment by afs** [comment]
#1527 changed `rsparql` to allow ARQ syntax.
