### ISSUE TITLE
Parsing of specific (broken) IRIs

### ISSUE THREAD

**Issue by dgrtner-ecc** [apache/jena#1669]
### Version

4.6.0

### Question

Hi,

we have the problem that our system parses update strings and a peculiar case is something like the following:

`DELETE DATA {GRAPH <http://graph/1> {<http://www.example.org/resource> <http://www.w3.org/2000/01/rdf-schema#isDefinedBy> <file:/some/path>. } }`

The <file:/some/path> becomes <file:///some/path> during the parsing by the UpdateFactory. Consequently the delete does not match the triple in the store. 

My question is if this can be controlled or prevented. Why does it happen?

thanks and best,
Denis

**Comment by afs** [comment]
It happens because `file:/some/path` is not an absolute URL (despite looking like it is). The parser sort this out making it `file:///`

A hierarchical URI (one that has a path) is `schema://authority/path?query#fragment`.
For a `file:` there is no authority section - it's empty. That leaves `file:///`. 

The same happens with "http:/path".

[RFC1738](https://datatracker.ietf.org/doc/html/rfc1738) is a bit loose.

How did the data get into the database?

The Java runtime (e.g. URL class) tends to write `file:/path` which is not a fully resolved URL.

The newer RFC is more lenient in the syntax but not the underlying resolved form. It allows the "//authority" to be omitted altogether but that is a relative URL and the resolved form is `file:///`

https://datatracker.ietf.org/doc/html/rfc8089

**Comment by afs** [comment]
@dgrtner-ecc How did the data get into the database? (did Jena miss something?)

It is possible to work with bad URIs using `FILTER(string test of str(?varFromPattern))` replacing `<file:/some/path>` with ?varFromPattern.

**Comment by afs** [comment]
Hmm - GSP should be parsed.
