### ISSUE TITLE
Graph.isIsomorphicWith doesn't work with blank nodes in quoted triples

### ISSUE THREAD

**Issue by Ostrzyciel** [apache/jena#1710]
### Version

4.7.0

### What happened?

When checking for isomorphism between two `Graph`s, Jena is supposed not to check for exact equality between blank nodes, but rather use a fancier isomorphism algorithm. This, however, seems not to be not true for quoted triples.

File `data/source.nt`:
```
_:b0 <http://example/p> <http://example/o> .
<< _:b0 <http://example/p> <http://example/o> >> <http://example/q> "ABC" .
```

Code:
```java
package org.example;

import org.apache.jena.riot.Lang;
import org.apache.jena.riot.RDFDataMgr;

public class Main {
    public static void main(String[] args) {
        var g1 = RDFDataMgr.loadGraph("data/source.nt", Lang.NT);
        var g2 = RDFDataMgr.loadGraph("data/source.nt", Lang.NT);
        System.out.println(g1.isIsomorphicWith(g2));
    }
}
```

This prints "false" instead of "true".

I encountered this problem when writing a test suite where I wanted to ensure that the input and output graphs are isomorphic. Quoted blank nodes seem to be the only case where this fails (all other RDF-star works fine).

I also tried to circumvent this by first converting both graphs into their reified forms (with `org.apache.jena.system.RDFStar`), but this failed too.

I have no idea how to even attempt fixing this, so I'll probably be of not much more help. But at least I can say that the issue is not critical to me :)

### Are you interested in making a pull request?

I don't understand the relevant internals, no.

**Comment by afs** [comment]
Try `IsoMatcher.isomorphic(Graph, Graph)`. `IsoMatcher` handles quoted triples correctly.

`IsoMatcher` is a naive (= simplistic back tracking) on collections of list of terms. Rows, in other words. It gets used for SPARQL result set checking and for graph isomorphism in tests. It was easier to adapt to RDF-star and applies to more than just graphs.

`RDFStar.encodeAsRDF` introduces a URN per unique quoted triple and the URN is based on the hash of quoted triple which makes the URN sensitive to the blank node label. This break the isomorphism but conversely is better for streaming. (Otherwise the process needs to keep state of seen blank nodes, which at scale consumes memory.)

**Comment by Ostrzyciel** [comment]
Thank you, it works! :)

I've submitted a quick PR to (hopefully) help clarify this in the javadoc.

**Comment by afs** [comment]
Thanks!
