### ISSUE TITLE
Poor performance Json LD 1.1 deserialization

### ISSUE THREAD

**Issue by cdekok** [apache/jena#1732]
### Version

4.7

### What happened?

The change to Json LD 1.1 deserialization has a big impact on performance, it causes a lot of CPU usage when the default changed to 1.1 when we upgraded Jena our application was about 3x as slow, changing this back to the `Lang.JSONLD10` fixed this, but seeing as the new default is 1.1 it might need some performance tweaks.

### Are you interested in making a pull request?

None

**Comment by cdekok** [comment]
Ah I didn't analyze it deep but as it's using titanium it seems it's a known issue https://github.com/filip26/titanium-json-ld/issues/184 so I guess that's probably where it should be improved but looking at the discussion not much will happen without any pr's which is fair, though maybe it could be made clear in the docs somewhere.

**Comment by afs** [comment]
This seems to be an Titanium issue.

If there is some way Jena can use Titanium in a more efficient manner, please reopen this issue with new information.

Otherwise, short of forking and rewriting some of the Titanium code, there appears to be nothing to be done by Jena for this issue.

FYI: At Jena5, later this year (hopefully), we are planning on dropping JSON-LD 1.0 support. The jsonld-java project is still looking for a maintainer and project has not had a release since  Dec 13, 2021.

JSON_LD related constants are to be deprecated in Jena 4.9.0 to prepare for this.

**Comment by cdekok** [comment]
Thanks for the information we will need to take some action in the future either solve the perfomance issues in titanium or migrate to a different format.
