### ISSUE TITLE
Fuseki UI sometimes doesn't load

### ISSUE THREAD

**Issue by SimonBin** [apache/jena#1749]
### Version

4.8.0-SNAPSHOT

### What happened?

I apologise for this very vague bug report. I also don't expect any action, I just want to write it down in case someone can add more details.

The issue is as follows: sometimes the fuseki Query UI does not load. To reproduce it (fairly frequently) on our installation, I used a link like this:

```
https://XXXXXXXXXXXX/#/dataset/YYYYYYYYYYYY/query?query=PREFIX%20units%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Fdef%2Fuom%2FOGC%2F1.0%2F%3E%0APREFIX%20geo%3A%20%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20spatial%3A%20%3Chttp%3A%2F%2Fjena.apache.org%2Fspatial%23%3E%0A%0Aselect%20distinct%20%3Ffeature%20%3Ftype%20%3FxgeoL%20%7B%0A%20%20values%20%3FmyPoint%20%7B%0A%20%20%20%20%22Point%2822.83736%2033.38213%29%22%5E%5Egeo%3AwktLiteral%0A%20%20%7D%0A%20%20%3Ffeature%20spatial%3AnearbyGeom%28%3FmyPoint%20100%20units%3Akilometre%29%20.%0A%20%20%3Ffeature%20rdfs%3Alabel%20%3FxgeoL%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20a%20%3Ftype%20.%0A%7D
```

put it on a website and opened it in private window mode

Then, the browser would only render the fuseki header (datasets/manage/help/server status green) and the rest of the page would not load (show as blank page). the browser would continue to show the loading indicator

In the Developer Tools, I could observe an unhandled/unconsumed request for Query-abcdef.js that was hanging there

I found a bug report which sounds similar https://github.com/storybookjs/builder-vite/issues/439

I reverted back to webpack on our custom installation for the time being

### Are you interested in making a pull request?

None

**Comment by kinow** [comment]
HI @SimonBin ,

I haven't seen this issue, but I will try to reproduce it locally. What's your setup? Are you running everything from Eclipse/IntelliJ, or maybe `mvn package` and then start some other way using jars?

There's a workaround in the issue you linked (looks like a great find! :+1:), we can try that, although it's really inconvenient to have to list all dependencies in another part of the configuration (I will probably try to debug a little more to understand the issue and only suggest this workaround as last option before a new release).

Cheers
Bruno

**Comment by SimonBin** [comment]
our setup is done with maven package of fuseki-main and https://github.com/AKSW/fuseki-mods/tree/adaptions/jena-fmod-ui

I will check tomorrow if this issue is easily reproduced on our site with  yarn run serve

**Comment by SimonBin** [comment]
> I will check tomorrow if this issue is easily reproduced on our site with yarn run serve
so far couldn't reproduce it from yarn :( tried with yarn run serve and yarn run serve:offline

**Comment by kinow** [comment]
> > I will check tomorrow if this issue is easily reproduced on our site with yarn run serve
> 
> so far couldn't reproduce it from yarn :( tried with yarn run serve and yarn run serve:offline

Hi @SimonBin 

Thanks for testing it out.

When we run with Yarn, using `vite preview` for instance, the application is built differently than when we run `mvn package`. The latter will perform a production build, that involves some optimization.

From the comments from that issue you linked, and after your tests, I think it confirms there's something in the build chain that is causing this loading issue in the generated assets.

Here's what I would try (you can try if you have time, but I will do so over next days when I have time):

1. Change `pom.xml` and `package.json` to produce a development build instead of a production build.

When you run `yarn run build` or `npx vite build`, you should be able to see a log line like "vite v4.0.4 building for production...". You can change the build mode with `npx vite build --mode development` or `yarn run build --mode development`. You can change the arguments of the Maven execution `yarn run build` of the `frontend-maven-plugin` plug-in.

2. Review the build options of Vite, trying some out and seeing if any fixes the issue (or makes it always happen).
3. Try what was mentioned in the issue you linked.
4. Not my favorite, but sometimes I have to read the source code of Vue/Vite/etc and hack my local copy or check it out and build it locally + link to test things out... just in case nothing fixes it.

Cheers
-Bruno

**Comment by SimonBin** [comment]
I finally got to try your idea (1), and even with `yarn run build --mode development` and output: `vite v4.0.4 building for development...`, when I run the complete package I **still get the same issue** (not loading in Firefox private window when going to https://docs.coypu.org/SparqlSampleQueries.html and right-click=>try it=>open in private window); the JS files are also minimized

I cannot easily seem to reproduce the error in Chrome. 

On navigate-back, I get this error in the Firefox Developer console--before that it just hangs:
```
Loading failed for the module with source “https://skynet.coypu.org/static/Query-94d5ecfb.js”. [skynet.coypu.org:25:70]
TypeError: error loading dynamically imported module
[index-e6a049f6.js:762:21220]
```

<details><summary>Hanging looks like this: </summary>

![image](https://user-images.githubusercontent.com/10867832/232029237-ec894192-11be-4a62-8d61-daa50584a415.png)

</details>

**Comment by kinow** [comment]
Thanks for the log and screenshot @SimonBin . I had a play with the Jena Fuseki in the link you provided. I tried clicking on random links, querying the datasets, hitting some not authorized errors, etc. Always going back and forth using the browser history. Unfortunately I was not able to reproduce the issue.

I noticed one outdated configuration in our build tools, but I do not think that would be causing this issue (you are welcome to test it, if you have time). I will try to reproduce it again someday later and update the PR if I find anything. Feel free to comment here if you find anything else useful :slightly_smiling_face: 

Thanks!
-Bruno

**Comment by SimonBin** [comment]
thanks for the patch, it needs a small change to compile: https://github.com/AKSW/jena/commit/df517ca34d51b3bedd22a8ebab83a0fae7e59702

sadly it doesn't influence this issue :(

<details><summary>Screencast of issue</summary>

[Screencast from 2023-04-17 10-22-05.webm](https://user-images.githubusercontent.com/10867832/232428178-2132aa51-9dbd-4589-ace4-a6ea624d48ce.webm)

</details>

**Comment by SimonBin** [comment]
> It could be an issue as you pointed in Vite or Vue. But I think that would be simpler to reproduce for others.

you are definitely right, maybe this is an issue with our set-up entirely unrelated to vite. what lead me to suspect vite was that reverting your webpack->vite  commit created a UI version where I did *not* manage to reproduce this issue

I will try to reproduce it with a more plain vanilla jena

thanks for your time on this issue!

**Comment by kinow** [comment]
>what lead me to suspect vite was that reverting your webpack->vite commit created a UI version where I did not manage to reproduce this issue

Hmmm, interesting. I could be that the server now is receiving more requests and not being able to handle it... or it could be an issue with some vite/vue setting (like optimization).

>thanks for your time on this issue!

Not a problem, thanks for the patience too. Next time I have time to work on this, I will try some different ways to reproduce it. If I manage to do so I can start debugging and trying to understand in which part of our build process or code the problem is.
