### ISSUE TITLE
Java modules used in Jena

### ISSUE THREAD

**Issue by supermaxiste** [apache/jena#1760]
### Version

4.7.0

### Question

Hello,

on the Apache Jena website it says that Jena4 requires Java 11. I was wondering which Java modules are specifically used in Jena4.

To give a bit of context, I'm trying to build a Dockerfile with a Jena-based tool. Previous developers used [OpenJDK containers](https://hub.docker.com/_/openjdk) for anything Jena related, but these containers are now deprecated because of new modular options (for example [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)). The problem for me is that these options specify exactly the java modules used and I can't seem to find this information for Jena4.

Best,
Stefan

**Comment by afs** [comment]
Jena requires java11 for the JVM and its security fixes and performance improvements. As a general policy, the project tries to support 2 LTS versions of Jena though the exact transition is on a case-by-case basis. The project runs development CI builds on several Java versions later than the requirement.

All the jars are have `automatic.module.name` and the relationship between them can be found with `mvn dependence:tree`.
To do Java JPMS for Jena needs the changes to package structure. It is also the case users do use classes that are not "public" API, simply due to the fact the code base predates JPMS by quite a long time.

The [dockerfile for Fuseki](https://github.com/apache/jena/blob/main/jena-fuseki2/jena-fuseki-docker/Dockerfile) includes a step that determines the Java JDK modules needed.

(This issue prompted me to update the dockerfile)
