### ISSUE TITLE
`ParserSupport` contains redundant `char < 0` check

### ISSUE THREAD

**Issue by Marcono1234** [apache/jena#1864]
### Version

ba2cdb6211f60d7725d779a8556266a8c0b2d0c5

### What happened?

The following files contain a redundant `s.charAt(i) < 0` check. `charAt` returns a `char` and the minimum value of `char` is 0, so it cannot be `< 0`.

https://github.com/apache/jena/blob/ba2cdb6211f60d7725d779a8556266a8c0b2d0c5/jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput/impl/ParserSupport.java#L129
https://github.com/apache/jena/blob/ba2cdb6211f60d7725d779a8556266a8c0b2d0c5/jena-core/src/main/java/org/apache/jena/rdfxml/xmlinput0/impl/ParserSupport.java#L129

### Are you interested in making a pull request?

No

**Comment by afs** [comment]
Hi @Marcono1234 -- yes, it's excessively safe code (likely either the optimizer will remove it or will be a zero cost instruction in the execution pipeline because the value is also used in the rest of the expression).

xmlinput0 is legacy - the original code for the parser before the current efforts maintaining the RDF/XML parser. 

xmlinput is the RDF/XML parser in-use in release Jena 4.8.0. 

There is development work to simplify the structure. ARP (the internalname for the parse) It has many features that have been added or existed when it was a standalone codebase.

I've made the change on my current active development so it does not get forgotten. This code, when finished, will become "xmlinput" and the current xmlinput (renamed to xmlinput1) will be the new legacy.

As a project Jena has always tried to support legacy behaviour for as long as possible. Each situation is treated individually. Jena has a long-tail of version usage so it helps users when they jump several versions.

More:
https://lists.apache.org/thread/zom28q9dqc7h4mx8s4v6h28c6b9sx2qh
