### ISSUE TITLE
Error server: Can't find resourceBase

### ISSUE THREAD

**Issue by ZookieSwag** [apache/jena#1882]
### Version

4.9.0

### Question

When trying to run the jena-fuseki2/jena-fuseki-docker/docker compose, I get this error:
![image](https://github.com/apache/jena/assets/35275686/b8ffa812-c2ee-4602-b989-ca90f3743fa3)
I made a modification to the docker build file to give it a custom Jar file
Docker build file changes:
![image](https://github.com/apache/jena/assets/35275686/5c31e38c-823f-465e-9a2f-c4010eead2f5)
and this is the only file modification made for the jar. It is in the turtle.jj file:
![image](https://github.com/apache/jena/assets/35275686/c4cf54d4-7441-479c-8344-be7de07537ed)

Can someone help me with this please?

**Comment by afs** [comment]
Hi @ZookieSwag,

There are several things going on here. 

1 -- That Turtle parser only exists to support long-time test code in jena-core. It is in the test jar and never makes it into to any Fuseki server. PR #1884 moves it out of the way to make this clearer. 

The Turtle parser in is normally the one in RIOT (artifact `jana-arq`) that is not generated with javacc for efficiency reasons, it hand written and is more than x2 faster.. There is a Turtle parser in  RIOT at `org.apache.jena.riot.lang.extra.TurtleJCC` which is accessible in Fuseki with content type `text/turtle-jcc`.

Could you describe what you are achieve with the change being made so we can help you?

2 -- `jena-fuseki-server` and `jena-fuseki-full-jar` are different. The first is Fuseki Main and currently does not have a UI. The second, as found in apache-jena-fuseki.zip has a companion `webapp/` directory which has the UI in it.

**Comment by ZookieSwag** [comment]
Hi @afs, currently the parser deletes multiple spaces in a row and new lines. I would like to change the parser so it will ignore excess spaces and new lines.

**Comment by ZookieSwag** [comment]
@afs Sorry, I think I might be using the wrong terminology. What I need it the turtle parser here for graphs:
![image](https://github.com/apache/jena/assets/35275686/7ddc9a41-15dd-4989-9969-bd97741152c9)
To keep the new lines made and display them in the vocabulary software I am using called "Skosmos". When I save the graph, it automatically removes the new lines.
![image](https://github.com/apache/jena/assets/35275686/4a17ae1c-ca42-4d95-afd9-40bf3a14d7c3)

**Comment by rvesse** [comment]
New lines are not permitted in single quoted literals unless you explicitly escape them as a `\n` so the input graph you show should technically be considered invalid syntax.  If you want to use literal new line characters within a literal then you should use the triple quoted form instead

> '\' (U+005C) may not appear in any quoted literal except as part of an escape sequence. Other restrictions depend on the delimiter:
>
> - Literals delimited by ' (U+0027), may not contain the characters ', LF (U+000A), or CR (U+000D).
> - Literals delimited by ", may not contain the characters ", LF, or CR.
> - Literals delimited by ''' may not contain the sequence of characters '''.
> - Literals delimited by """ may not contain the sequence of characters """.

See [RDF 1.1 Turtle - Quoted Literals](https://www.w3.org/TR/turtle/#turtle-literals)

OTOH just because you use triple quoted literals on the input doesn't mean Jena will use them in the output.  Jena is free to use whatever serialised form of the data it wants provided it preserves the semantics of the data.

This kinda sounds like an XY problem to me.  Presumably Skosmos isn't doing a good job of rendering literals with appropriate formatting and/or wrapping? So you've jumped to needing to modify the Jena parsers. The real solution is more likely a bug report against Skosmos asking them to improve how they render literals within their UI?

**Comment by ZookieSwag** [comment]
Thank you, I will look into that
