### ISSUE TITLE
How can I make tdb2.xloader continue loading when the loading accidentally interrupt?

### ISSUE THREAD

**Issue by xilixii** [apache/jena#1951]
### Version

4.8.0

### Question

This afternoon I was using tdb2.xloader to load a 120G ttl file into the database, but it was accidentally interrupted halfway, but the loading has reached the POS stage, how can I continue building on the basis of what has already been built. It takes me seven hours to built this database, I would be appreciate if this seven hours is not wasted.
The command I use to load the ttl file is
```
tdb2.xloader --loc /xxx --threads 100 xxx.ttl
```

**Comment by afs** [comment]
Hi @xilixii,

It's technically possible but not supported.

If you look in the main script, you'll see it is a series of calls to other scripts to do each of the steps. They could be run separately by hacking the script if none of the files, including the intermediate working files in the temporary directory, have been touched at all. 

That's time consuming for the user so it is probably easier (quicker) to rerun. `disown` helps to reduce the risk of accidentally killing it.

BTW a large number of threads, more than the number of cores, usually doesn't give an improvement. But may be you have a large machine.

Approximately how many triples are in the TTL file? `tdb2.tdbloader --loader=parallel` on a large server-class machine with local SSD/NVMe may be faster.

**Comment by xilixii** [comment]
Thank you for your  reply @afs,
It is about 1,400,000,000 triples in the TTL file. I know that it is recommanded to set the threads by the number of cpu cores minus one. And I did use a server-class machine with 104 cores, so it is ok.
BTW I have rerunned tdb2.xloader. I would like to try the option --loader=parallel next time.

**Comment by xilixii** [comment]
I have received the same error again, @afs 
I just rerun the command 
```
tdb2.xloader --loc xxx --threads 100 xxx
```
And It was stuck at the stage of Build POS with no info output on screen for about 2 hours which seems unnormal, then it occurs to this error:
<img width="713" alt="image" src="https://github.com/apache/jena/assets/76767481/4253b09f-ded0-45ce-a912-0bb32e3746ad">
I use a ssh connection to manipulate a server machine remotely. I don't know whether it is caused by the ssh connection problem or the tdb2.xloader problem.

**Comment by rvesse** [comment]
So if you are going to run this on a remote machine via a ssh session `disown` is likely not enough as a terminal disconnect, e.g. due to no output for a long time, still interrupts the process so you likely need `nohup` instead (aside [`disown` vs `nohup` explained](https://unix.stackexchange.com/a/148698))

So ideally you want something like the following:

```bash
$ nohup tdb2.xloader <your-args> > load.txt &
$ tail -f load.txt
```

So launch into with `nohup` to disassociate from the terminal and redirects its output to `load.txt` and places the process into the background.  Thus even if your `ssh` session disconnects the process continues running.  You can then monitor the process by tailing the log file, and you should also be able to see it in `ps`, `top` etc.

Then if you get disconnected you can then reconnect and simply resume monitoring by tailing the log file, `ps`, `top` and so on

--

An alternative workaround would be set up SSH Keepalive for your connection so long pauses in terminal output don't cause a disconnect.  See `ServerAliveInterval` in the [`ssh_config` man page](https://linux.die.net/man/5/ssh_config)

**Comment by xilixii** [comment]
Your comment seems to be very helpful, Appreciate that @rvesse 
I will try this again, but I still worried whether it is a ssh problem or not. It failed on the same stage ```Build POS``` twice. And this time it was stuck on this ```Build POS``` stage for two hours. I am not sure about whether it is normal to be stuck at ```Build POS``` for such a long time. I mean, is there any chance to be a bug of ```tdb2.xloader``` script?
However it is most likely caused by ssh connection problem. Any I will try ```nohup``` to rerun again, if it works then it means there is no problem with ```tdb2.xloader``` scripts.

**Comment by xilixii** [comment]
I have successfully load the TTL file into TDB2 database by ```nohup```. Thank you for your comment @rvesse

**Comment by afs** [comment]
Glad to hear you've loaded the data.

`client_loop: send disconnect` is an SSH message.

The xloader goes quiet because there a large sort going on and the sort program does not output it's progress. We could add a "hello I'm stil working on it" but it would not indicate how far through the task.

The different indexes, SPO, POS, OSP can take quite different lengths of time to prepare using the sort - the first SPO is often shorter so I guess that's why no timeout happened.
