### ISSUE TITLE
UnmodifiableGraph does not work as expected

### ISSUE THREAD

**Issue by sszuev** [apache/jena#1990]
### Version

4.9.0

### What happened?

Expect all modify operations are prohibited.
```java
import org.apache.jena.graph.Graph;
import org.apache.jena.graph.NodeFactory;
import org.apache.jena.graph.Triple;
import org.apache.jena.sparql.graph.GraphFactory;

public class TmpUnmodifiableGraph {

    public static void main(String[] args) {
        Graph graph = new org.apache.jena.sparql.graph.UnmodifiableGraph(GraphFactory.createGraphMem());
        try {
            graph.add(Triple.create(NodeFactory.createURI("a"), NodeFactory.createURI("b"), NodeFactory.createURI("c")));
            throw new AssertionError();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

This is quite an old problem (also in 3.x.x)
So, probably, this is by design. But strange.

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
#1991 should address the issue.

It is draft at the moment.

**Comment by afs** [comment]
It's a consequence of the wrapper pattern. `UnmodifiableGraph.add` calls `base.add` which will calls `base.performAdd`.

`UnmodifiableGraph` would need to intercept `add(Triple)` and `delete(Triple)`, as well as `remove` and `clear`.

But probably better to delete it because there is `GraphReadOnly` (#1991 fixes immutability for the prefixmapping).
