### ISSUE TITLE
Forcing usage of caffeine 2.x

### ISSUE THREAD

**Issue by rjrudin** [apache/jena#2132]
### Version

4.10.0

### Question

Hello - my team is looking to include jena-arq in a Java application for which we would like to maintain Java 8 as the minimum version. The caffeine 3.x dependency forces Java 11 as a minimum version.

I changed our Gradle configuration to force usage of the latest caffeine 2.x library:

```
implementation("org.apache.jena:jena-arq:4.10.0") {
    exclude module: "caffeine"
}
implementation "com.github.ben-manes.caffeine:caffeine:2.9.3"
```

And initial testing shows that this seemingly just works, though our usage of Jena is fairly simple right now:

1. Read files via `AsyncParser` and `RDFParserBuilder`.
2. Build a `Graph` containing triples and use `RDFWriter` to write out triples in `NTRIPLES` format.

Just wondering if there any gotchas to be aware of? Didn't find anything of interest in a search on "caffeine" through this repository, so hoping this does in fact just work.

**Comment by afs** [comment]
Hi @rjrudin - I take it you recompiled parts of the source code. Jena4 as released is compiled for Java11.

The project policy is "last two LTS versions". Jena5 will require Java17.

The project has to find a balance with the limited resources available. It also has to remain interesting for the contributors. 

It isn't a matter of simply creating a branch because security issues must be dealt with across all active artifacts that the project produces. Some of the dependencies no longer support Java8. Remaining on old versions of dependencies isn't sustainable because of addressing vulnerabilities reported in CVEs.

I don't remember that having been a lot of activity to convert existing code to use any Java11 language features.
Jena4 jena-arq does use Java11 `java.net.http`. Jena4 uses Eclipse Jetty10 which requires Java11.

**Comment by rjrudin** [comment]
Thanks @afs  - my mistake too as while I had changed the Gradle settings, I was still testing with Java 11 and thus everything worked fine. Totally understand about requiring Java 11 or higher. I'll close this as my question was based on my error.
