### ISSUE TITLE
reasoners should support owl:AllDisjointClasses

### ISSUE THREAD

**Issue by tobiaswjohn** [apache/jena#2151]
### Version

4.10

### Feature

As far as I see, no reasoner supports `owl:AllDisjointClasses` constructs (also implicitly mentioned in the [documentation](https://jena.apache.org/documentation/inference/index.html#validation)).
E.g. for the following example (turtle syntax), the inferred model does not contain pairwise `owl:disjointWith` statements between the three classes (as one might expect).
```
[ rdf:type owl:AllDisjointClasses ;
  owl:members ( :A
                :B
                :C
              )
] .
```

However, they are not produced. This leads (for me) to unintuitive behavior, as this information is then not used when I perform a validity check on the inferred model, whereas the standard `owl:disjointWith` is supported (at least with the "full" and "mini" reasoner). 
I work a lot with OWL ontologies created with Protege, which commonly creates `owl:AllDisjointClass` constructs, so i run into this issue rather often.

 Is there a particular reason why this construct is not supported? If not, I think this would be a very helpful feature.

PS: as far as I can see, this also applies to  `AllDisjointProperties`

### Are you interested in contributing a solution yourself?

No

**Comment by rvesse** [comment]
Primarily because none of the developers who originally wrote the reasoner code are actively involved in the project anymore.  None of our remaining active developers understand that portion of the code base to do anything more than fix the occasional obvious bug (e.g. NPE) that might be reported.

Expanding the capabilities of the current reasoners would require sufficiently knowledgeable developer(s) to develop and contribute those new features/enhancements to the project.

**Comment by afs** [comment]
`owl:AllDisjointClasses` is from OWL2, together with `owl:AllDisjointProperties`.

OWL1, which Jena provides, has only `owl:AllDifferent`.

See coverage: https://jena.apache.org/documentation/inference/index.html#OWLcoverage

**Comment by tobiaswjohn** [comment]
Thank you for the clarification. I wrongly assumed that "OWL" also meant "OWL 2".

**Comment by afs** [comment]
I've created an issue for OWL2 support: #2160
