### ISSUE TITLE
Fails to get a TURTLE-writer when upgrading to 3.17.0 or higher

### ISSUE THREAD

**Issue by roygronmo** [apache/jena#2300]
### Version

4.0.0

### What happened?

We get a problem when upgrading Jena-core from 3.15.0 to 4.0.0 (the problem arises between 3.16.0 and 3.17.0): the TURTLE writer is no longer available.

The call to Model::write with parameters new StringWriter() and «TURTLE» will generate an error:

org.apache.jena.shared.NoWriterForLangException: Writer not found: RIOT

When debugging it seams that the map containing allowed values no longer contains «TURTLE»
However, the documentation of the write() method says that «TURTLE» still should be supported:
The language in which to write the model is specified by the lang argument. Predefined values are "RDF/XML", "RDF/XML-ABBREV", "N-TRIPLE", "TURTLE", (and "TTL") and "N3". The default value, represented by null is "RDF/XML".

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
> org.apache.jena.shared.NoWriterForLangException: Writer not found: RIOT

There seems to be something else going on if the writer is called "RIOT" maybe to do with the classpath.

Jena 4.0.0 is itself quite old. Matters may have been fixed since then.

The current 4.x version is 4.10.0 and is the last 4.x series. There are [significant security fixes](https://jena.apache.org/about_jena/security-advisories.html) and also security fixes in dependencies.

The next version is 5.0.0  which requires Java17.

While `Model::write` remains for legacy reasons, the more up-to-date way to write is either `RDFDataMgr` or for  precise control of writer setup, `org.apache.jena.riot.RDFWriter`.

**Comment by roygronmo** [comment]
Thank you. I upgraded to jena 4.10.0, but I am a bit skeptic to using 5.0.0, since it is only a release candidate (rc1).

The following code works:
```
    public static String convertToTurtle(Model description) {
        try (ByteArrayOutputStream modelWriter = new ByteArrayOutputStream();) {
        RDFWriter.source(description)
                 .format(RDFFormat.TURTLE)
                 .output(modelWriter);
            return modelWriter.toString(StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new NrkTechnicalException("Failed to serialize model as TURTLE", e);
        }
    }
```

**Comment by afs** [comment]
Looks good. Hope that sorts your usage out.

Minor:
There is also `output(StringWriter)` - not deprecated. Generally Jena discourages java.io.Reader/java.io.Writer because of the recurrent character set issues but Stringreader/StringWriter have their uses.

Re: jena5.0.0
Hopefully next month. "RC1" here means "finished", with now wider "Review".

The advantage to you is that a major version change may include some breaking changes; it also has many deprecations removed.

But 4.10.0 to 5.x (small x) should not be too painful.

The top-level motivation for 4->5 is the change to requiring Java17 and `java.servlet` to `jakarta.servlet`.
