### ISSUE TITLE
NullPointerException - Cannot enter synchronized block because "this.coordinatorLock" is null

### ISSUE THREAD

**Issue by aliariff** [apache/jena#2318]
### Version

4.10.0

### What happened?

We got NullPointerException when there is some concurrent access to the dataset. One accesses tries to shut down/close the dataset, while the other still tries to open it.

### Relevant output and stacktrace

```shell
java.lang.NullPointerException: Cannot enter synchronized block because "this.coordinatorLock" is null
    at org.apache.jena.dboe.transaction.txn.TransactionCoordinator.begin$(TransactionCoordinator.java:635)
    at org.apache.jena.dboe.transaction.txn.TransactionCoordinator.begin(TransactionCoordinator.java:627)
    at org.apache.jena.dboe.transaction.txn.TransactionCoordinator.begin(TransactionCoordinator.java:599)
    at org.apache.jena.dboe.transaction.txn.TransactionalBase.begin(TransactionalBase.java:110)
    at org.apache.jena.dboe.storage.system.DatasetGraphStorage.begin(DatasetGraphStorage.java:68)
    at org.apache.jena.sparql.core.DatasetGraphWrapper.begin(DatasetGraphWrapper.java:261)
    at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.begin(DatasetGraphTxnCtl.java:75)
    at org.apache.jena.sparql.core.DatasetImpl.begin(DatasetImpl.java:114)
(The rest are our internal code)
...............
...............
...............
```

### Are you interested in making a pull request?

Maybe

**Comment by rvesse** [comment]
You are going to need to provide some more context here (eg example code) about how the different threads are using the Dataset as it isn't clear from one small stack trace how this situation would arise

**Comment by aliariff** [comment]
Hi @rvesse,

I know a code example would be ideal here. Unfortunately, I can't spend additional time creating a PoC on how this can be reproduced. But I can give direction or at least a logical reason why this could happen.

Before going to this line https://github.com/apache/jena/blob/jena-4.10.0/jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java#L635

I think we also should put an additional check `checkActive();` like in https://github.com/apache/jena/blob/jena-4.10.0/jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java#L637

Because it can be the case that between these lines https://github.com/apache/jena/blob/jena-4.10.0/jena-db/jena-dboe-transaction/src/main/java/org/apache/jena/dboe/transaction/txn/TransactionCoordinator.java#L610-L627
Some other thread is shutting down the TransactionCoordinator.

My analysis could be wrong here cause I just spent a little time reading the code. But at least that is how I reason such a thing could happen.

**Comment by afs** [comment]
Hi @aliariff 

As background, could you say what the application is trying to achieve by calling shutdown() / close() and shutting down the TransactionCoordinator?

**Comment by aliariff** [comment]
Hi @afs 

Yes, we indeed perform manual/force release on certain situations using `TDBInternal.expel(dsg);` (Ref: https://jena.apache.org/documentation/tdb/faqs.html#fuseki-tdb-memory-leak).

> We can add some checkNotShutdown but that is still going to throw an exception, albeit with a better type and message.

Yes, that is exactly my goal here, exception should be fine but at least a meaningful one by throw a `TransactionException` instead of NPE.

**Comment by afs** [comment]
@aliariff wrote:
> Yes, we indeed perform manual/force release on certain situations using `TDBInternal.expel(dsg);` (Ref: https://jena.apache.org/documentation/tdb/faqs.html#fuseki-tdb-memory-leak).

Note that is about TDB1.

TDB2 performs write-ahead into database itself (MVCC) during a write transaction and doesn't have a post-transaction clear-up step and the Fuseki+TDB1 related issue doesn't occur.

Also on the page:

>> Using transactions is strongly recommended

... and for TDB2, transactions are required.

>> Should I use an SSD?

Yes!

**Comment by aliariff** [comment]
Hi @afs, 

Thank you for the explanation. However, based on our observations, manually using expel alleviates the memory problem.

Yet, within the scope of this ticket, the null pointer exception issue remains unresolved and needs to be improved with better exceptions.

**Comment by afs** [comment]
> we indeed perform manual/force release on certain situations

What are those situations? 
I'm not clear why you need this when there are other threads still trying to use the database. 

Even if completely expelled and rebuilt, all that happens is that the node cache is lost and rebuilt. The rest of TDB2 memory usages isn't in the heap.

**Comment by aliariff** [comment]
In our applications, we open many tdb2 connections, and it is also quite common that the tdb connection must be closed and recreated to a new location due to our business application logic (reloading a dataset, etc). We don't reuse the same folder location to avoid conflict or inconsistency.

What we observe during this close/open is that only calling `.close()` on the dataset is not enough, as we still see the mapped buffer pool is not cleared & that causes an issue because we now open a new connection, hence it is continuously increasing and never goes down, that lead to the app crashed. That is the reason we introduce this `.expel()`, which also call `.shutdown()` internally. 

After we call this `.expel()` together with `.close()`, the memory usage decreases.

**Comment by afs** [comment]
> we open many tdb2 connections

"There can be only one" :-) per database.

> the memory usage decreases.

If that is heap, then it is the node cache - it's an LRU cache and the bytes size depends on the size of the nodes cached. By default, it has a limit of 1 million entries (increasing the size has not been seen to lead to significant gains). Node cache will reappear in the new location.

The RES (Resident RAM) will drop due to files - that's the OS file system cache for a closed file; RES goes up and down anyway while the database is running and is controlled by the kernel. VIRT will drop, possibly a lot, but all of VIRT that isn't also RES is not resident and has no performance effect and is meaningless.

Sounds like you could seemlessly switch to a reloaded database using the same logic as the `DatasetGraphSwitchable`  which is the  java object the app has a handle on. (Not use unchanged - it's tied to the TDB2 compaction and carries some location details.)

**Comment by rvesse** [comment]
Another thing to consider if you have a predominantly read heavy workload and your datasets are relatively small is to just store them on disk in a single file using a format like Jena's RDF Thrift.  You can then read them into a memory dataset directly from the data file rather than creating TDB datasets.  The load overheard is going to be higher but you'd probably get more predictable memory release vs TDB and that might be an acceptable trade off.

Obviously if your workload involves a lot of write operations then this isn't a viable option
