### ISSUE TITLE
java.lang.Error: Maximum lock count exceeded

### ISSUE THREAD

**Issue by awoestmann** [apache/jena#2584]
### Version

4.9.0

### What happened?

After about a week of runtime our server just returns the error below and is no longer recoverable without a restart.

This seems to be similiar to #1499.

### Relevant output and stacktrace

```shell
java.lang.Error: Maximum lock count exceeded
    at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.fullTryAcquireShared(ReentrantReadWriteLock.java:535)
    at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryAcquireShared(ReentrantReadWriteLock.java:494)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1078)
    at java.base/java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:738)
    at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.beginMultiMode(DatasetGraphTxnCtl.java:334)
    at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.tryNonExclusiveMode(DatasetGraphTxnCtl.java:252)
    at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.enterTransaction(DatasetGraphTxnCtl.java:110)
    at org.apache.jena.dboe.storage.system.DatasetGraphTxnCtl.begin(DatasetGraphTxnCtl.java:74)
    at org.apache.jena.sparql.core.DatasetImpl.begin(DatasetImpl.java:114)
[...]
```

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
Hi @awoestmann - could you give some context because the stacktrace isn't enough to investigate.

* What is the server configuration - the stack trace has `DatasetImpl` so is it some kind of configuration file setup.
* What operation of the server is this occurring at the time of the stacktrace?
* How is data loaded into this dataset?
* Is it HTTP/1 or HTTP/2 connections to the server?
* Are calling clients properly ending their closing their HTTP connections?

**Comment by awoestmann** [comment]
Hi @afs,

thanks for quick reply.

I will try to give you some context:

> What is the server configuration - the stack trace has DatasetImpl so is it some kind of configuration file setup.

I am not entirely sure what you mean here. We are creating the dataset using something like:

```java
Dataset dataset = TDB2Factory.connectDataset("path/to/tdb/dir")
```

> What operation of the server is this occurring at the time of the stacktrace?

At the time of the stacktrace the server is handling a request that should return the result of a sparql query. The error then occurs when we start the transaction to execute the query:

```java
    dataset.begin(TxnType.READ);
    try {
      //Execute query and return result
    } finally {
      dataset.end();
    }
```

> How is data loaded into this dataset?

Like mentioned above we are using `TDB2Factory.connectDataset(String location)` once when the REST-Controller is created.

> Is it HTTP/1 or HTTP/2 connections to the server?

We only have HTTP/1 connections.

> Are calling clients properly ending their closing their HTTP connections?

It looks like the connections are closed properly, we could not find any requests with connections that have been aborted before the response was sent.

**Comment by rvesse** [comment]
> > What is the server configuration - the stack trace has DatasetImpl so is it some kind of configuration file setup.
>
> I am not entirely sure what you mean here. We are creating the dataset using something like:

Andy initially assumed that this was an issue with the Fuseki server provided by the project, likely because the potential related issue you referenced was specific to Fuseki.

> Like mentioned above we are using `TDB2Factory.connectDataset(String location)` once when the REST-Controller is created.

Are you certain that is only gets created once?  Depending on what REST framework you are using there's no guarantee that it doesn't create and destroy instances of your REST controller over the lifetime of your server, have you tried adding some logging to verify whether this is the case?

The REST framework used may be a pertinent detail here.

**Comment by afs** [comment]
Yes, I was assuming this was inside Fuseki because of the link to #1499.
 
`TDB2Factory.connectDataset` returns the same dataset on all calls for the same location. There's a `computeIfAbsent` cache. 
There shouldn't be a need to create it more than once and keep an object reference.

Is the `TDB2Factory.connectDataset` always was same directory path?

I'm assuming that writes are not blocking before this problem is seen.

It looks like somewhere that is a code path which is not ending a read transaction code.
That's what was behind #1499.

**Comment by awoestmann** [comment]
> Yes, I was assuming this was inside Fuseki because of the link to https://github.com/apache/jena/issues/1499.

Sorry for the confusion there.

> Is the TDB2Factory.connectDataset always was same directory path?

The path is read from a config file and should not change during the runtime.

> 
> Are you certain that is only gets created once? Depending on what REST framework you are using there's no guarantee that it doesn't create and destroy instances of your REST controller over the lifetime of your server, have you tried adding some logging to verify whether this is the case?
> 
> The REST framework used may be a pertinent detail here.
> 

We are using Spring boot for this application. The dataset is created in the constructor of a `@ApplicationScope` repository class that is injected in the REST-Controller. So i would think that there should only be one instance of the dataset.

I will add some logging and try to confirm that there is only a single instance.

**Comment by awoestmann** [comment]
My first test in a development environment looks promising:

The application hast processed 109k requests without any issue, whereas before the error occurred after less than 60k requests.

**Comment by afs** [comment]
Excellent. The lock count limit is 64k.

I've also tested with Java21 virtual threads. They behave the same as platform threads (where one thread that use one OS thread). Same situation - the lock limit applies to virtual threads.

PR #2605.
