### ISSUE TITLE
is this well formed rdf xml?

### ISSUE THREAD

**Issue by justin2004** [apache/jena#2626]
### Version

5.1.0

### Question

```
$ ~/apache-jena-5.1.0/bin/riot --validate ro.owl                                     
05:42:55 WARN  riot            :: [line: 16257, col: 45] Bad IRI: <urn:swrl#e> Code: 61/SCHEME_PATTERN_MATCH_FAILED in PATH: The scheme specific syntax rules are violated.                                                                                                     
05:42:55 WARN  riot            :: [line: 16260, col: 45] Bad IRI: <urn:swrl#d> Code: 61/SCHEME_PATTERN_MATCH_FAILED in PATH: The scheme specific syntax rules are violated.
...
```

one of the offending lines:
```
<rdf:Description rdf:about="urn:swrl#e">
```

[matentzn](https://github.com/matentzn) thinks it might be well formed rdf xml:
https://github.com/oborel/obo-relations/issues/803

**Comment by rvesse** [comment]
Yes it is well formed RDF/XML or Jena would have produced a parser error

You have received a warning because as the warning states the URI used doesn't meet the rules for the `urn` URI scheme. Jena still processes it just fine it's just making you aware you have potential issues in your data

FWIW there's plenty of malformed `urn` URIs out in the wild, it's not necessarily a problem unless your data encounters a system that strictly enforced URI scheme rules

**Comment by afs** [comment]
URNs have two mandatory parts NID and NSS

` "urn" ":" NID ":" NSS`

Namespace Identifier (NID)
Namespace Specific String (NSS)

https://datatracker.ietf.org/doc/html/rfc8141

**Comment by justin2004** [comment]
thanks guys!
